title: Huyền Chip
description: > # this means to ignore newlines until "baseurl:"
  Blog nghĩ vặt của Huyền Chip 
permalink: ':title/'
baseurl: "/vn" # the subpath of your site, e.g. /blog
url: "https://huyenchip.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: chipro #if your site has a twitter account, enter it here

# Author Settings
author: Huyền Chip
author-img: chip.jpg
about-author: Tác giả của "Xách ba lô lên và Đi". Kỹ sư trí tuệ nhân tạo. Hay nghĩ vặt.
social-twitter: chipro
social-facebook: chipiscrazy
social-instagram: huyenchip19
social-github: chiphuyen
social-linkedin: chiphuyen
social-email: chip@huyenchip.com

# Disqus
discus-identifier: https-huyenchip-com-vn # add your discus identifier

# Tracker
analytics: UA-103070243-3 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
